# WallMaze 게임 소스 파일
WALLMAZE_SRC := $(GAMES_DIR)/wallmaze/wallmaze_state.cpp \
                $(GAMES_DIR)/wallmaze/wallmaze_state_pathfinding.cpp \
                $(GAMES_DIR)/wallmaze/zobrist_hash.cpp

# WallMaze 알고리즘 파일
WALLMAZE_ALGO :=