# ConnectFour 게임 소스 파일
CONNECT_FOUR_SRC := $(GAMES_DIR)/connect_four/connect_four_state.cpp \
                   $(GAMES_DIR)/connect_four/connect_four_bitboard.cpp

# ConnectFour 알고리즘 파일 (커넥트 포 특화 알고리즘이 있다면 추가)
CONNECT_FOUR_ALGO :=